.\"	$Id$
.\"
.\" Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ACME-CLIENT.CONF 5
.Os
.Sh NAME
.Nm acme-client.conf
.Nd acme-client configuration file
.Sh DESCRIPTION
The
.Nm
file describes the domains processed by
.Xr acme-client 1 .
A configuration consists primarily of certificate authorities and
domains:
.Bd -literal
authority custom {
  agreement url https://example.com/agreement.pdf
  api url https://api.example.com/directory
  account key /etc/ssl/private/my-acme.key
}

domain myname.com {
  alternative names { www.myname.com }
  sign with custom
}
.Ed
.Pp
The top level may also include variable assignments and file
inclusions.
.Sh AUTHORITIES
Certificate authorities are defined in top-level blocks as follows:
.Bd -literal
authority name { ... }
.Ed
.Pp
Each authority must specify the following:
.Bl -tag -width Ds
.It Cm agreement url Ar url
The agreement
.Ar url .
.It Cm api url Ar url
The
.Ar url
for accessing the authority's directory service.
.El
.Pp
The following are optional:
.Bl -tag -width Ds
.It Cm account key Ar file
The account key
.Ar file .
This should
.El
.Sh DOMAINS
.Sh ASSIGNMENTS
.Sh INCLUSIONS
.Sh SEE ALSO
.Xr acme-client 1
.Sh HISTORY
The
.Nm
file format first appeared in
.Ox 6.1
and was the basis for this format and its parser.
This version of the file and parser was written by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv .
